spring:
  config:
    import:
      - api-config.yml
      - app-config.yml
      - persistence-config.yml
      - security-config.yml
      - optional:file:.env[.properties]

livekit:
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}
  server:
    url: ${LIVEKIT_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    moe.kanata: DEBUG

---
spring:
  config:
    activate:
      on-profile: main

logging:
  level:
    moe.kanata: DEBUG