spring:
  config:
    import:
      - api-config.yml
      - app-config.yml
      - persistence-config.yml
      - security-config.yml
      - optional:file:.env[.properties]

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    moe.kanata: DEBUG

---
spring:
  config:
    activate:
      on-profile: main

logging:
  level:
    moe.kanata: DEBUG